diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: "left_wheel_joint"
  right_wheel: "right_wheel_joint"
  publish_rate: 50
  command_topic: "/cmd_vel"
  odom_frame_id: "odom"
  base_frame_id: "base_link"
  wheel_separation: 0.4
  wheel_radius: 0.025   
  velocity_rolling_window_size: 10
  enable_odom_tf: true
  pose_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.001, 0.0, 0.0, 0.0, 0.001]
  twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.001, 0.0, 0.0, 0.0, 0.001]

gazebo_ros_control:
  pid_gains:
    left_wheel_joint:
      p: 100.0
      i: 0.0
      d: 0.0
    right_wheel_joint:
      p: 100.0
      i: 0.0
      d: 0.0
